In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/play-tennis/play_tennis (1).csv


In [2]:
# importing the libraries
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
# loading the data
df=pd.read_csv('/kaggle/input/play-tennis/play_tennis (1).csv')
df.head()

day   outlook  temp humidity    wind play
0  D1     Sunny   Hot     High    Weak   No
1  D2     Sunny   Hot     High  Strong   No
2  D3  Overcast   Hot     High    Weak  Yes
3  D4      Rain  Mild     High    Weak  Yes
4  D5      Rain  Cool   Normal    Weak  Yes

In [4]:
# droping the columns
df.drop(columns=['day'],inplace=True)

In [5]:
df.head()

outlook  temp humidity    wind play
0     Sunny   Hot     High    Weak   No
1     Sunny   Hot     High  Strong   No
2  Overcast   Hot     High    Weak  Yes
3      Rain  Mild     High    Weak  Yes
4      Rain  Cool   Normal    Weak  Yes

In [6]:
# splitting the data for x and y
x=df.drop(columns=['play'])
y=df.play.ravel()
y

/tmp/ipykernel_1665/1248247000.py:2: FutureWarning: Series.ravel is deprecated. The underlying array is already 1D, so ravel is not necessary.  Use `to_numpy()` for conversion to a numpy array instead.
  y=df.play.ravel()


array(['No', 'No', 'Yes', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes', 'Yes',
       'Yes', 'Yes', 'Yes', 'No'], dtype=object)

In [9]:
# one hot encoding
from sklearn.preprocessing import OneHotEncoder
ohe = OneHotEncoder(drop='first',sparse=False,dtype=np.int32)

x= ohe.fit_transform(x[['outlook','temp','humidity','wind']])
x

/opt/conda/lib/python3.10/site-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(


array([[0, 1, 1, 0, 0, 1],
       [0, 1, 1, 0, 0, 0],
       [0, 0, 1, 0, 0, 1],
       [1, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 1, 1],
       [1, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 1, 0, 1, 0, 1],
       [0, 1, 0, 0, 1, 1],
       [1, 0, 0, 1, 1, 1],
       [0, 1, 0, 1, 1, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 1, 1],
       [1, 0, 0, 1, 0, 0]], dtype=int32)

In [10]:
print(y)

# label encoding
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
y=le.fit_transform(y)
y

['No' 'No' 'Yes' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'Yes' 'Yes' 'Yes' 'Yes'
 'No']


array([0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 0])

In [11]:
# importing the model
from sklearn.naive_bayes import CategoricalNB
from sklearn.metrics import accuracy_score


In [12]:
nb_classifier=CategoricalNB()

# model_fitting
nb_classifier.fit(x,y)

CategoricalNB()

In [13]:
# model_prediction
y_pred = nb_classifier.predict(x)
y_pred

array([0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1])

In [14]:
# accuracy
print(accuracy_score(y,y_pred))

0.8571428571428571


In [15]:
# prediction on new_data
x1 = np.array([0, 1, 1, 0, 0, 0]).reshape(1, -1)
nb_classifier.predict(x1)

array([0])

In [25]:
# prediction on new_data

x2 = np.array([0, 1, 0, 1, 1, 0]).reshape(1, -1)
nb_classifier.predict(x2)

array([1])